### ISSUE TITLE
库冲突

### ISSUE THREAD

**Issue by lin1520050767** [qiniu/dart-sdk#41]
七牛库和很多其他的库都有crypto的冲突，类似lottie, auto_router等等，应该尽快升级库
Because auto_route_generator >=1.0.2 depends on build ^2.0.0 which depends on crypto ^3.0.0, auto_route_generator >=1.0.2 requires crypto ^3.0.0.
And because every version of qiniu_sdk_base depends on crypto ^2.1.5, auto_route_generator >=1.0.2 is incompatible with qiniu_sdk_base.
And because qiniu_flutter_sdk 0.2.0 depends on qiniu_sdk_base ^0.2.0 and no versions of qiniu_flutter_sdk match >0.2.0 <0.3.0, auto_route_generator >=1.0.2 is incompatible with qiniu_flutter_sdk ^0.2.0.
So, because ahlan_shop depends on both qiniu_flutter_sdk ^0.2.0 and auto_route_generator ^1.0.2, version solving failed.
pub get failed (1; So, because ahlan_shop depends on both qiniu_flutter_sdk ^0.2.0 and auto_route_generator ^1.0.2, version solving failed.)

**Comment by huangbinjie** [comment]
看起来是你们用了 Null Safety 的版本，我们因为一些愿意还没做好升级的准备，详情请看 #40 

这边先关了
