### ISSUE TITLE
support for flutter web

### ISSUE THREAD

**Issue by gitldx2** [qiniu/dart-sdk#45]
目前的sdk 要求的参数File 不是html.File，无法直接在web中使用。
另外我想在网页中上传图片，用了Flutter官方提供的image_picker_for_web 图片选择插件，不过这个插件所返回的图片对象是没有本地文件地址的，所以无法提供File对象，这样就无法在客户端直传七牛云了，请问七牛能考虑这样的应用场景，提供web版的sdk吗？

**Comment by yinxulai** [comment]
感谢建议，我们会在内部评估一下，在近期会在此进行答复。

**Comment by huangbinjie** [comment]
@gitldx2 打算提供一个 putBytes 接口，能否满足你的需求？

另外我们碰到了 dio 在 web 上不兼容的问题：https://github.com/flutterchina/dio/issues/1030 暂时无法兼容 web

**Comment by bailyzheng** [comment]
希望支持flutter web +1

**Comment by bailyzheng** [comment]
> 感谢建议，我们会在内部评估一下，在近期会在此进行答复。

咋样了？既然做了就做完美嘛，支持web才能真正实现跨平台，从你们实现的角度看与其他平台也是一致的，做一下我们开发者省了好多事

**Comment by yinxulai** [comment]
0.4.0 已经发布，支持 web
