### ISSUE TITLE
没有提供删除对象的方法吗?

### ISSUE THREAD

**Issue by xSILENCEx** [qiniu/dart-sdk#51]
目前 flutter sdk 是否提供了文件的删除方法?

**Comment by yinxulai** [comment]
由于删除需要使用 `AK/SK` 对请求进行签名，而目前的 `Flutter SDK` 定位是客户端 `SDK`
在我们的[安全指南](https://developer.qiniu.com/kodo/1644/security)中，`SK` 不允许包含在分发给最终用户的程序中，
所以 `Flutter SDK` 通过不提供消费 `AK/SK` 的程序接口来避免用户写出违背安全指南的代码。

如果你有需求，推荐通过自己的服务端转发（并签名）删除请求提供给你的客户端程序调用，这样你就可以把 `AK/SK` 存储在你的服务端，降低安全风险。

**Comment by xSILENCEx** [comment]
@yinxulai  好的，感谢解答
