### ISSUE TITLE
如何获取上传文件尺寸、宽高比、大小、时长等。

### ISSUE THREAD

**Issue by 657447158** [qiniu/dart-sdk#52]

**Comment by yinxulai** [comment]
1、文件的尺寸/大小可以通过文件本身的 `size` 属性拿到
2、图片宽高比获取办法很多，简单点可以通过 `img` 标签来获取

#### 上面两个问题本质与 SDK 无关，这里仅给出建议，更多细节请参考相关文档。

#### 如果时长是指上传从开始到结束花费的时间的话，可以通过下面的办法获取：

在任务开始时记录一个时刻，在上传结束时再记录一个时刻，两个时刻的差即为花费的时间。

**Comment by yinxulai** [comment]
如果你想获取的上传之后的文件信息，可以通过生成 `token` 时，在 `returnBody` 内使用魔法变量来获取，具体参考文档：https://developer.qiniu.com/kodo/1235/vars

**Comment by 657447158** [comment]
@yinxulai 感谢。这里还有个问题，用这个SDK上传图片后返回的是一个key和hash，那么这种情况如何通过这个访问地址+参数的形式去获取图片的缩略图呢？
