### ISSUE TITLE
关于缩略图

### ISSUE THREAD

**Issue by 657447158** [qiniu/dart-sdk#53]
上传图片后返回的是一个key和hash，那么这种情况如何通过这个访问地址+参数的形式去获取图片的缩略图呢？
如何获取上传图片的缩略图。

**Comment by huangbinjie** [comment]
看起来你是不太懂如何拼接访问地址？[文档](https://developer.qiniu.com/kodo/kb/1321/how-to-acquire-the-outside-storage-file-links?category=kb)里有的，这类问题请不要提在 sdk 这边

**Comment by yinxulai** [comment]
关于如何获取资源的下载地址请参考：https://developer.qiniu.com/kodo/1232/download-process
关于通过参数获取缩略图请参考：https://developer.qiniu.com/dora/1279/basic-processing-images-imageview2

**Comment by yinxulai** [comment]
还有其他问题吗？
