### ISSUE TITLE
是否支持上传url的文件？

### ISSUE THREAD

**Issue by lizhuoyuan** [qiniu/dart-sdk#55]
比如一个图，图片地址是www.xxx.png
能否直接upload('www.xxx.png')?
或者作为一个future？

**Comment by huangbinjie** [comment]
暂时还不支持，可以先尝试调用这个[接口](https://developer.qiniu.com/kodo/4097/asynch-fetch)

**Comment by lizhuoyuan** [comment]
七牛sdk 有提供方法  期待以后支持
https://github.com/qiniu/java-sdk/blob/master/examples/FetchDemo.java

**Comment by huangbinjie** [comment]
@lizhuoyuan  这个接口是需要签名的，而签名是需要 ak, sk 的。flutter-sdk 是跑在客户端的～
你看到那些支持了的都是服务端 sdk，比如 java-sdk. 不排除我们以后会有服务端的 dart-sdk

**Comment by lizhuoyuan** [comment]
> 

草率了，看java以为是安卓的来着。
