### ISSUE TITLE
When to release a new version to pub.dev ?

### ISSUE THREAD

**Issue by litang0908** [qiniu/dart-sdk#57]
Just want merge this PR https://github.com/qiniu/dart-sdk/pull/54

**Comment by huangbinjie** [comment]
The version `0.3.3` of `qiniu_sdk_base` has already been published yet. If you have already installed `qiniu_flutter_sdk` to your project, you may need to delete the `pubspec.lock` file, and then install the new one.

**Comment by litang0908** [comment]
Thanks !!!
