### ISSUE TITLE
使用Custom 的 hostProvider时，分片上传视频失败

### ISSUE THREAD

**Issue by lyb5834** [qiniu/dart-sdk#59]
提示 `StorageError [StorageErrorType.RESPONSE, 400]: {error: invalid multipart format: request Content-Type isn't multipart/form-data}`

设置强制表单上传 `forceBySingle：true`  时可以上传

**Comment by yinxulai** [comment]
感谢反馈，我们正在查看相关信息

**Comment by huangbinjie** [comment]
我记得分片默认的 `Content-Type` 是 `octet-stream`，是不是你的后台做了上传类型限制的事情

**Comment by lyb5834** [comment]
> @lyb5834 我记得分片默认的 `Content-Type` 是 `octet-stream`，是不是你的后台做了上传类型限制的事情

是吗？可是iOS端Android端的七牛SDK支持分片上传的啊，就flutter版本的不行，一模一样 的地址

**Comment by yinxulai** [comment]
是不是 CustomHostProvider 实现里的地址不正确导致的？
使用 CustomHostProvider 你们应该是私有云？
方便留个联系方式我们确定一下服务端版本，看看是否有不一致的地方
联系方式发送到 yinxulai@qiniu.com

**Comment by huangbinjie** [comment]
之后我们会支持 v1 上传，目前 dart-sdk 没有办法，麻烦使用接口上传哈
