### ISSUE TITLE
不支持上传到东南亚地域

### ISSUE THREAD

**Issue by zhouyyibin** [qiniu/dart-sdk#60]
上传到东南亚地域，会报如下错，也没有提供可以指定地域的方法
lutter: StorageError [StorageErrorType.RESPONSE, 400]: {error: incorrect region, please use up-as0.qiniup.com, bucket is: english-word1}

**Comment by huangbinjie** [comment]
@zhouyyibin 是否有自定义过 `Config.Host` ?

**Comment by zhouyyibin** [comment]
@huangbinjie 
没有自定义过

这是我的代码
static final Storage _storage = Storage();
static updateFile(String file) async {
      await _storage
          .putFile(File(file), response.data,
              options: PutOptions(controller: putController))
          .then((value) async =>
              {print("success")})
          .catchError((onError) => {print(onError.toString())});
}

结果返回了如下错误：
lutter: StorageError [StorageErrorType.RESPONSE, 400]: {error: incorrect region, please use up-as0.qiniup.com, bucket is: english-word1}

我用华南地域的bucket就不会报错了。用新加坡的bucket就会报上面的错。我之所以用新加坡的bucket，是因为我的域名没有备案，所以只能用海外的bucket。

**Comment by huangbinjie** [comment]
@zhouyyibin 请问你是否先用了华南再切换到东南亚的时候没有重启 App 过吧

**Comment by zhouyyibin** [comment]
应该是。我卸载了APP，然后重新安装，现在可以了

**Comment by huangbinjie** [comment]
问题解决了的话，我就先关了
