### ISSUE TITLE
pub 上的 Readme 有 typo

### ISSUE THREAD

**Issue by bruce3x** [qiniu/dart-sdk#61]
<img width="674" alt="image" src="https://user-images.githubusercontent.com/15318754/204704525-fcbdd458-6c25-473a-a68d-b25a542d021a.png">

应该是 `qiniu_flutter_sdk`

**Comment by huangbinjie** [comment]
有没有兴趣提个 pr

**Comment by bruce3x** [comment]
看起来你们[最新的提交](https://github.com/qiniu/dart-sdk/commit/950c8d9612059e35de4efd3fa323138ccd7223cd)就是修复这个 typo 只是没有发版到 pub
