### ISSUE TITLE
麻烦问一下，上传报错的问题

### ISSUE THREAD

**Issue by ProfessionalMe** [qiniu/dart-sdk#73]
我的DIO版本号是：  dio: ^5.2.1+1
sdk是：0.5.0 
上传图片提示这个错，但是不影响上传。

`[🔔 Dio] _MultiStream<List<int>> cannot be used to imply a default content-type, please set a proper content-type in the request.
         #0      ImplyContentTypeInterceptor.onRequest (package:dio/src/interceptors/imply_content_type.dart:45:36)
         #1      DioMixin.fetch.requestInterceptorWrapper.<anonymous closure>.<anonymous closure> (package:dio/src/dio_mixin.dart:385:26)
         #2      new Future.<anonymous closure> (dart:async/future.dart:256:37)
         #3      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
         #4      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
         #5      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
         #6      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)
[🔔 Dio] _MultiStream<List<int>> cannot be used to imply a default content-type, please set a proper content-type in the request.
         #0      ImplyContentTypeInterceptor.onRequest (package:dio/src/interceptors/imply_content_type.dart:45:36)
         #1      DioMixin.fetch.requestInterceptorWrapper.<anonymous closure>.<anonymous closure> (package:dio/src/dio_mixin.dart:385:26)
         #2      new Future.<anonymous closure> (dart:async/future.dart:256:37)
         #3      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
         #4      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
         #5      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
         #6      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)`

**Comment by bachue** [comment]
@ProfessionalMe  请升级到 v0.6.0 再试试看

**Comment by yinxulai** [comment]
fix in #87
