### ISSUE TITLE
分片上传dio报错

### ISSUE THREAD

**Issue by saturnpeng** [qiniu/dart-sdk#77]
_MultiStream<List<int>> cannot be used to imply a default content-type, please set a proper content-type in the request.

**Comment by bladeofgod** [comment]
same issue!

**Comment by dudukee** [comment]
+1

**Comment by bachue** [comment]
@saturnpeng @bladeofgod @dudukee   请升级到 v0.6.0 再试试看

**Comment by yinxulai** [comment]
fix in #87
